### ISSUE TITLE
gemコマンドでのインストールについて

### ISSUE THREAD

**Issue by 5atk6** [masa16/pwrake#2]
gemコマンド実行後に
`rbenv rehash`
の実行も記載してもらえると助かります。
私の場合、gemコマンドによるインストールは成功したのですが、その後pwrakeコマンドを実行しても

> -bash: pwrake: command not found

と、エラーが出てしまったので。

**Comment by masa16** [comment]
コメントありがとうございます。
READMEに記載しました。
